### ISSUE TITLE
We don't use GitHub Discussions in our OSS projects anymore

### ISSUE THREAD

**Issue by suzuki-shunsuke** [suzuki-shunsuke/suzuki-shunsuke#2]
We'll stop using GitHub Discussions in our OSS projects.
Please use GitHub Issues instead.

We still enable GitHub Discussions in some projects to keep existing discussions, but we won't accept new discussions.
If new discussions will be created, we'll close them.

## How to stop GitHub Discussions

- Remove unused categories and templates
- Rename categories to `Deprecated (<original name>)`
  - https://github.com/orgs/aquaproj/discussions

<img width="276" alt="image" src="https://github.com/user-attachments/assets/a07d0114-da18-4f7b-801e-cf9376dafd0c">

- Modify templates to prevent people from creating new discussions
  - Rename template files to `deprecated-<original name>`
  - https://github.com/aquaproj/aqua/blob/8f3d325206d11fc94d33be0dd4ac091d8b4c2fdf/.github/DISCUSSION_TEMPLATE/deprecated-bug-report.yml

```yaml
title: Deprecated (Bug Report)
body:
  - type: markdown
    attributes:
      value: |
        # :warning: Please create an Issue instead

        [We don't accept new discussions anymore](https://github.com/aquaproj/aqua/issues/3311).
        We keep this discussion category only for existing discussions.

        [Please create an issue](https://github.com/aquaproj/aqua/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml).
  # At least one input item is required, so we add a dummy checkbox.
  - type: checkboxes
    attributes:
      label: .
      options:
        - label: ..
```

- Add a GitHub Actions Workflow to close new discussions
  - https://github.com/aquaproj/aqua/blob/8f3d325206d11fc94d33be0dd4ac091d8b4c2fdf/.github/workflows/close-discussion.yaml
- Create this issue and issues in each repository
  - e.g. https://github.com/aquaproj/aqua/issues/3311
- Update CONTRIBUTING.md
- Migrate Discussion Templates to Issue Templates
  - https://github.com/aquaproj/aqua/tree/8f3d325206d11fc94d33be0dd4ac091d8b4c2fdf/.github/ISSUE_TEMPLATE

## Why?

- To manage our OSS tasks in a single GitHub Project
- To aggregate information in GitHub Issues
- To make the operation simple
  - To reduce options and avoid unnecessary hesitation
- GitHub Issues are more powerful than GitHub Discussions at the moment

## Manage our OSS tasks in a single GitHub Project

We maintain a lot of OSS projects, and we gather their issues and pull requests into a single GitHub Project.

https://github.com/orgs/szksh-lab/projects/1/views/1

[Please see also our blog post](https://dev.to/suzukishunsuke/pull-together-github-issues-and-pull-requests-across-repositories-to-github-projects-automatically-a87).

This approach works pretty well, but GitHub Discussion can't be managed in GitHub Projects.

## Gather tickets in GitHub Issues

If we use both GitHub Issues and Discussions, tickets and information would be dispersed between them.
For example, even if we search information in GitHub Issues, we can't find information in GitHub Discussions.
Sometimes people aren't sure whether to create Issues or Discussions.
Sometimes we aren't sure if we should move Issues to Discussions or not.

## Discussion's features make confusion

Discussions has some features Issues doesn't.
They are useful but they make confusion too.
Sometimes we aren't sure if we should close answered Discussions.
Sometimes we feel stress when we expect reply but people add new comments.

## Using both Issues and Discussions makes operation and rules complicated

To use both Issues and Discussions well, we need some operation, rules, and automation.
This makes the management complicated.
We need more simple way.

## GitHub Issues is more powerful than GitHub Issues

- Issues can be managed by GitHub Projects
- Code of the same repository with GitHub Issues is shown in GitHub Discussions

![image](https://github.com/user-attachments/assets/4c767deb-6257-4f4e-8c86-5c780d03775a)

- `#<issue number>` becomes a link to the issue in GitHub Releases
- When other issues and pull requests refer to an Issue, it is shown in the timeline of the issue

![image](https://github.com/user-attachments/assets/2644fcd4-6142-429e-935d-cca4a2f9d6f6)

- Edit history is shown in the timeline

<img width="618" alt="image" src="https://github.com/user-attachments/assets/5a72a297-ed9c-4579-a394-b4f0a55bc94b">

- We can assign people to Issues
- We can add Issues to Milestones

We can solve these problems by creating Issues after discussing in GitHub Discussions.
But it's bothersom to create Issues based on Discussions.
And we can't manage topics in Projects until we create Issues.
Now we can manage Issues by Projects well, so the problem of Discussions is undesirable for us.

## Q&A

We're aware that some people disagree with our decision.

### Discussions suits for `free form` discusion

https://github.com/aquaproj/aqua/issues/1666#issuecomment-1516558466

> Makes sense to simplify but I did find it confusing as I thought discussions was better for "free form" discussion that didn't have a specific code related issue.

We understand the idea that GitHub Discussions suit for "free form" discussion.

We think we can solve the problem to some extent by providing good Issue Templates.

We are still considering if we should allow issues without templates.
We hesitate to allow issues without templates because google issue templates improve the quality of Issues.
But it's hard to prepare good issue templates suiting for any use cases.

### How about creating Discussions first and creating Issues after discussion in Discussions?

Some projects allow only maintainers to create Issues.

- Ghostty: https://x.com/mitchellh/status/1852039089547309552
- Renovate: https://github.com/renovatebot/renovate?tab=readme-ov-file#issues-and-discussions

I think this approach is nice, but this approach doesn't suit for our projects.

## Related Discussions

- https://github.com/aquaproj/aqua/issues/1930
- https://github.com/aquaproj/aqua/issues/1666
